#!/bin/bash

arg_error_msg=$'\r\nList of arguments. Please enter one of the following:\r\n'
arg_error_msg=$arg_error_msg$' ARG1 - mode\r\n'
arg_error_msg=$arg_error_msg$'  -e text encoding\r\n'
arg_error_msg=$arg_error_msg$'  -d text decoding\r\n'
arg_error_msg=$arg_error_msg$' ARG2 - the main text\r\n'

mode=${1}
arg=${2}

encoded=""
decoded=""
salt="FGt%4gdT65Hfbfjk^f45v"


if [ "$arg" == "" ] || [ "$mode" == "" ]
then
	echo "Empty parameters. $arg_error_msg"
	exit
fi


encode(){
	pass=${1}
	encoded=`echo "$pass" | openssl aes-256-cbc -a -pbkdf2 -salt -pass pass:"$salt"`
}

decode(){
	pass=${1}
	decoded=`echo "$pass" | openssl aes-256-cbc -a -pbkdf2 -d -salt -pass pass:"$salt"`
}



if [ "$mode" == "-e" ]
then 
	encode "$arg"
	echo "$encoded"
elif [ "$mode" == "-d" ]
then 
	decode "$arg"
	echo "$decoded"
else
	echo "Unsupported format. $arg_error_msg"
	exit
fi



